- shell:
    - command: [apt-get install -y curl]
    - command: [curl -fsSLo /tmp/doctl-1.71.0-linux-amd64.tar.gz https://github.com/digitalocean/doctl/releases/download/v1.71.0/doctl-1.71.0-linux-amd64.tar.gz]
    - command: [tar -zxf /tmp/doctl-1.71.0-linux-amd64.tar.gz -C /tmp/]
    - command: [mv /tmp/doctl /usr/local/bin/doctl]
    - command: [rm /tmp/doctl-1.71.0-linux-amd64.tar.gz]
