- shell:
    - command: [add-apt-repository ppa:regolith-linux/release]
    - command: [apt-get update]
    - command: [apt-get install -y i3-gaps rofi compton compton-conf nitrogen feh xsettingsd lxappearance neofetch w3m-img imagemagick]

- link:
    ~/.config/i3/config: gui/i3/config 
    ~/.config/i3status/config: gui/i3status/config
    ~/.Xresources: gui/Xresources/config
    ~/.extend.Xresources: gui/Xresources/config.extend
    ~/.config/polybar/config: gui/polybar/config
    ~/.config/polybar/launch.sh: gui/polybar/launch.sh
    ~/.config/compton.conf: gui/compton/config
    ~/.config/wall.png: gui/Space.png
    ~/.dmenurc: gui/other/dmenurc

- create:
    - ~/.themes/
    - ~/.fonts/
    - ~/.icons/

- shell:
    - command: [cp -R gui/fonts/. ~/.fonts/]
    - command: [cp -R gui/themes/. ~/.themes/]
    - command: [cp -R gui/icons/. ~/.icons/]
