- shell:
    - command: [apt-get update]
    - command: [apt-get install -y curl]
    - command: [curl -sSl https://downloads.slack-edge.com/releases/linux/4.23.0/prod/x64/slack-desktop-4.23.0-amd64.deb -o ./slack-desktop-4.23.0-amd64.deb]
    - command: [ls -la]
    - command: [dpkg -i ./slack-desktop-4.23.0-amd64.deb]
    - command: [rm ./slack-desktop-4.23.0-amd64.deb]
