- shell:
    - command: [apt-get update]
    - command: [apt-get install -y curl]
    - command: [curl -sS https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg | sudo apt-key add -]
    - command: [echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list]
    - command: [apt-get update]
    - command: [apt-get install -y spotify-client]
