- link:
    ~/.vimrc: vim/vimrc

- shell:
    - command: [apt-get update && apt-get install -y curl]
    - command: [curl -sfLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim]
