- shell:
    - command: [apt-get update]
    - command: [apt-get install -y libxcb-xtest0]
    - command: [curl -sfLo /tmp/zoom_amd64.deb https://zoom.us/client/latest/zoom_amd64.deb]
    - command: [dpkg -i /tmp/zoom_amd64.deb]
    - command: [rm /tmp/zoom_amd64.deb]
