- shell:
  - command: [apt update && apt install -y zsh]
    description: Install Zsh
  - command: [sh zsh/configure-shell.sh]
    description: Configure zsh as main shell

- link:
    ~/.zshrc: zsh/zshrc
    ~/.oh-my-zsh/themes/robbyrussell.zsh-theme: zsh/themes/robbyrussel-customized.zsh-theme
