- shell:
  - command: [apt update && apt install -y zsh]
    description: Install Zsh
  - command: [sh ./meta/scripts/configure-shell.sh]
    description: Configure zsh as main shell

- link:
    ~/.zshrc: zsh/zshrc
